name: Maven Package

on:
  push: 
    branches:
      - sony-may-23

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B install --file pom.xml
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: jarfile
        path: ${{ github.workspace }}/target/spring-boot-testing-0.0.1-SNAPSHOT.jar
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
    - name: download jarfile
      uses: actions/download-artifact@v2
      with: 
        name: jarfile
        path: ${{ github.workspace }}
    - name: listing
      run: ls -ltr
